feat: Add `pg_cron` and Postgis
paradedb/charts pull request #44
Opened 2024-10-09 21:50 UTC by philippemnoel

# Ticket(s) Closed

- Closes #N/A

## What
We ship with these two extensions in ParadeDB Dockerfile as well, but had forgotten to add them to our Helm Chart setup. This fixes that.

TODOs
- [x] ~Add comment for `\c`~ -- Not necessary anymore: https://trac.osgeo.org/postgis/ticket/5125
- [x] Test that `pg_cron` and `postgis` work, and that the `cron.database_name` is correct
- [x] Add automatic install of `pg_cron`
- [x] Update instructions for testing
- [x] Final manual test on Minikube cluster

## Why
^

## How
^

## Tests
Need to do a final test

2024-10-09 22:25 UTC, philippemnoel commented
```bash
    {{- if eq .Values.type "paradedb" }}
    - CREATE EXTENSION IF NOT EXISTS pg_cron;
    {{- end }}
```

Doesn't seem to work, somehow

2024-10-10 06:28 UTC, itay-grudev requested changes

2024-10-10 06:28 UTC, itay-grudev commented on charts/paradedb/templates/_bootstrap.tpl
> +    {{- end }}
The way you've written this will prevent users from providing their own `postInitSQL`.

Rewrite it as:
```yaml
    postInitSQL:
      {{- if eq .Values.type "paradedb" }}
      - CREATE EXTENSION IF NOT EXISTS pg_cron;
      {{- end }}
      {{- with .Values.cluster.initdb }}
        {{- range .postInitSQL }}
          {{- printf "- %s" . | nindent 6 }}
        {{- end -}}
      {{- end }}
```

In addition you should add `postInitSQL` to the omit statement on line `6`.

2024-10-10 06:28 UTC, itay-grudev commented on charts/paradedb/values.yaml
> +    cron.database_name: postgres
You need to move this in the `postgresql.parameters` section.

```yaml
    parameters:
      cron.database_name: postgres
```

2024-10-10 06:28 UTC, itay-grudev commented on charts/paradedb/values.yaml
> -    #   - CREATE EXTENSION IF NOT EXISTS vector;
Why is this example removed? If you definitely want it gone, could you add `[]` to the line above so it remains valid if uncommented?

2024-10-10 06:30 UTC, itay-grudev commented
I think you'll also need to modify this test: https://github.com/paradedb/charts/blob/main/charts/paradedb/test/postgresql-cluster-configuration/01-non_default_configuration_cluster.yaml

2024-10-10 16:50 UTC, philippemnoel commented on charts/paradedb/templates/_bootstrap.tpl
> +    {{- end }}
Thank you!

2024-10-10 16:51 UTC, philippemnoel commented on charts/paradedb/values.yaml
> +    cron.database_name: postgres
thank you!

2024-10-10 16:52 UTC, philippemnoel commented on charts/paradedb/values.yaml
> -    #   - CREATE EXTENSION IF NOT EXISTS vector;
good catch thank you!

2024-10-10 16:53 UTC, philippemnoel commented
> I think you'll also need to modify this test: https://github.com/paradedb/charts/blob/main/charts/paradedb/test/postgresql-cluster-configuration/01-non_default_configuration_cluster.yaml
> 
> and it's assertion here:
> 
> https://github.com/paradedb/charts/blob/main/charts/paradedb/test/postgresql-cluster-configuration/01-non_default_configuration_cluster-assert.yaml

You mean this?

```bash
      postInitSQL:
        - CREATE TABLE mytable (id serial PRIMARY KEY, name VARCHAR(255));
```

To check that `create extension pg_cron;` works?

2024-10-10 17:13 UTC, itay-grudev commented
@philippemnoel Yes. The assertion should be that both your statement and the custom statement are set:

```
      postInitSQL:
        - CREATE EXTENSION IF NOT EXISTS pg_cron;
        - CREATE TABLE mytable (id serial PRIMARY KEY, name VARCHAR(255));
```

2024-10-10 18:20 UTC, philippemnoel commented
> @philippemnoel Yes. The assertion should be that both your statement and the custom statement are set:
> 
> ```
>       postInitSQL:
>         - CREATE EXTENSION IF NOT EXISTS pg_cron;
>         - CREATE TABLE mytable (id serial PRIMARY KEY, name VARCHAR(255));
> ```

Thank you!

2024-10-11 16:23 UTC, philippemnoel commented
helm upgrade --install paradedb \--namespace paradedb-database \--create-namespace \--values values.yaml \PATH_TO_CHART

2024-10-12 13:56 UTC, philippemnoel commented
Tested everything, works great.

2024-10-13 19:28 UTC, merged